### ISSUE TITLE
not supporting less3+

### ISSUE THREAD

**Issue by BananaAcid** [jescalan/accord#340]
using less version 2.7.2 it worked, but not anything newer.

```
Error: less version 3.8.1 is not currently supported
    at Object.exports.load (/Users/bananaacid/project3442/src/node_modules/accord/lib/index.js:29:13)
    at Object.<anonymous> (/Users/bananaacid/project3442/src/node_modules/gulp-less/index.js:9:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/bananaacid/project3442/src/dev/gulpfile.js:7:14)
```

**Comment by jescalan** [comment]
Hey there @BananaAcid! Are you on the most recent version of accord? The adapter should support anything through the `3.x` semver range: https://github.com/jescalan/accord/tree/master/lib/adapters/less

**Comment by jescalan** [comment]
Nice! Glad it worked out 😬
