### ISSUE TITLE
Support for less v4

### ISSUE THREAD

**Issue by mdel-cm** [jescalan/accord#361]
Hi,

I just tried to upgrade to less 4.0.0 in an existing project, which gives me the following error:
```
Error: less version 4.0.0 is not currently supported
    at Object.exports.load (C:\Users\mdel\git\devbox\git\sensum\node_modules\accord\lib\index.js:29:13)
    at Object.<anonymous> (C:\Users\mdel\git\devbox\git\sensum\node_modules\gulp-less\index.js:9:29)
    // Longer stack trace ...
```
Node: 14.15.1
Yarn: 1.22.10

I have been pointed here coming from: https://github.com/gulp-community/gulp-less/issues/312

Thanks and best regards,
Michael

**Comment by PengJiyuan** [comment]
Is this a dead repo ?

**Comment by jescalan** [comment]
Yes
